#!/bin/bash
cmd="$*"
lastFile=$(mktemp)

coproc { stdbuf -oL bash -c "$cmd"; }
exec 3<&${COPROC[0]} 4>&${COPROC[1]}

while read -ru 3 line; do
		if [[ $line == "@PUMP" ]]; then
				echo "@PUMP" >&4
		else
				echo "$line" >"$lastFile"
				echo "$line"
		fi
done </dev/null &

exec 6>&1

while read -r line; do
		if [[ ${line: -1} == '%' ]]; then
				line="${line::-1}$(<"$lastFile")"
				echo -e "\e[1A\r$line" >&6
		fi
		
		case "$line" in
				'!'*)
						IFS=$'!' read -r proc cmd <<<"${line:1}"

						echo "@ASK $proc"

						if [[ ${cmd: -1}  == ',' ]]; then
								echo "${cmd::-1}"
						else
								echo "$cmd"
								echo "@Y"
						fi
						;;
				*)
						echo "$line"
						;;
		esac
done >&4
