#!/bin/bash

watch="$1"
cmd="$2"

inp=$(mktemp -u)
trap 'rm -f $inp' EXIT

clear

exec 5<&0 6>&1

{
		(eval "$cmd" <&5 >&6) &

		while read -r _; do
				kill %eval
				clear
				(eval "$cmd" <&5 >&6 ) &

		done < <(inotifywait -me CLOSE_WRITE -r $watch)
}

